### ISSUE TITLE
Fix rspec deprecation warnings

### ISSUE THREAD

**Issue by justindowning** [justindowning/puppet-rbenv#34]
```
Deprecation Warnings:

Filtering by an `:example_group` subhash is deprecated. Use the subhash to filter directly instead. Called from /usr/local/opt/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/example.rb:12:in `block in <top (required)>'.
Filtering by an `:example_group` subhash is deprecated. Use the subhash to filter directly instead. Called from /usr/local/opt/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/example.rb:16:in `block in <top (required)>'.
Filtering by an `:example_group` subhash is deprecated. Use the subhash to filter directly instead. Called from /usr/local/opt/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/example.rb:20:in `block in <top (required)>'.
Too many uses of deprecated 'Filtering by an `:example_group` subhash'. Pass `--deprecation-out` or set `config.deprecation_stream` to a file for full output.

--------------------------------------------------------------------------------
RSpec::Puppet::ManifestMatchers::CreateGeneric implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /Users/justin/dev/gh/puppet-rbenv/spec/classes/rbenv_spec.rb:12:in `block (2 levels) in <top (required)>')
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
RSpec::Puppet::ManifestMatchers::CreateGeneric implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /Users/justin/dev/gh/puppet-rbenv/spec/classes/rbenv_spec.rb:31:in `block (2 levels) in <top (required)>')
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
RSpec::Puppet::ManifestMatchers::CreateGeneric implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /Users/justin/dev/gh/puppet-rbenv/spec/classes/rbenv_spec.rb:38:in `block (2 levels) in <top (required)>')
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
RSpec::Puppet::ManifestMatchers::CreateGeneric implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /Users/justin/dev/gh/puppet-rbenv/spec/defines/build_spec.rb:17:in `block (3 levels) in <top (required)>')
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
RSpec::Puppet::ManifestMatchers::CreateGeneric implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /Users/justin/dev/gh/puppet-rbenv/spec/defines/build_spec.rb:19:in `block (3 levels) in <top (required)>')
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
RSpec::Puppet::ManifestMatchers::CreateGeneric implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /Users/justin/dev/gh/puppet-rbenv/spec/defines/build_spec.rb:20:in `block (3 levels) in <top (required)>')
--------------------------------------------------------------------------------
Too many similar deprecation messages reported, disregarding further reports. Pass `--deprecation-out` or set `config.deprecation_stream` to a file for full output.

--------------------------------------------------------------------------------
RSpec::Puppet::ManifestMatchers::CreateGeneric implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /Users/justin/dev/gh/puppet-rbenv/spec/classes/rbenv_spec.rb:21:in `block (4 levels) in <top (required)>')
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
RSpec::Puppet::ManifestMatchers::CreateGeneric implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
(Used from /Users/justin/dev/gh/puppet-rbenv/spec/defines/build_spec.rb:35:in `block (4 levels) in <top (required)>')
--------------------------------------------------------------------------------


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

22 deprecation warnings total

Finished in 1.89 seconds (files took 0.68405 seconds to load)
20 examples, 0 failures
```

**Comment by justindowning** [comment]
Fixed in 12dfe5c5
